// Command msgmanifest writes docs/proto/twilight-msg-type-urls.json from the
// descriptor set scripts/export-proto-descriptor.sh has just built.
//
// The manifest used to be a heredoc in that script. CI regenerates the file and
// diffs it, but a heredoc regenerates to itself, so the check passed while the
// manifest went stale: the three authority-rotation messages were executable on
// the chain and absent from the file downstream decoders read (#69).
//
// The Twilight entries are now derived: every method of every `Msg` service in a
// `twilight.<module>.v1` package, in declaration order, with modules in the order
// their files appear in the set (the order the script passes them to protoc). The
// SDK-native entries are a deliberate choice rather than a projection, because
// most bank messages are signed only by a keyless authority and can never appear
// in a transaction. They are listed below and checked against the bank Msg
// service, so a renamed or removed one fails generation instead of shipping. The
// envelope names are checked the same way.
//
// app/encoding_test.go independently compares the result with what the app
// registers, so a message added without regenerating fails `go test`.
//
// Tooling only: it reads a descriptor file and writes JSON.
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"regexp"
	"strings"

	gogoproto "github.com/cosmos/gogoproto/proto"
	descriptorpb "github.com/cosmos/gogoproto/protoc-gen-gogo/descriptor"
)

const note = "Raw-tx decode: a CometBFT tx is cosmos.tx.v1beta1.TxRaw -> decode TxBody (TxRaw.body_bytes) -> for each TxBody.messages[] Any, match Any.type_url below and decode Any.value against the same fully-qualified message in twilight-descriptors.pb. All listed types resolve from that single descriptor set. Generated by scripts/export-proto-descriptor.sh."

// bankMsgs are the bank messages an account can sign: `tx bank send` and
// `tx bank multi-send`. Each must be a method input of cosmos.bank.v1beta1.Msg.
var bankMsgs = []string{
	"cosmos.bank.v1beta1.MsgSend",
	"cosmos.bank.v1beta1.MsgMultiSend",
}

var envelope = []field{
	{"tx_raw", "cosmos.tx.v1beta1.TxRaw"},
	{"tx", "cosmos.tx.v1beta1.Tx"},
	{"tx_body", "cosmos.tx.v1beta1.TxBody"},
	{"auth_info", "cosmos.tx.v1beta1.AuthInfo"},
	{"signer_info", "cosmos.tx.v1beta1.SignerInfo"},
	{"sign_mode", "cosmos.tx.signing.v1beta1.SignMode"},
}

var signerPubKeys = []string{
	"cosmos.crypto.secp256k1.PubKey",
	"cosmos.crypto.ed25519.PubKey",
	"cosmos.crypto.multisig.LegacyAminoPubKey",
}

var twilightPackage = regexp.MustCompile(`^twilight\.([a-z]+)\.v1$`)

type field struct{ key, value string }

func main() {
	descPath := flag.String("descriptor", "", "path to the FileDescriptorSet")
	outPath := flag.String("out", "", "path of the manifest to write")
	flag.Parse()
	if *descPath == "" || *outPath == "" {
		fmt.Fprintln(os.Stderr, "usage: msgmanifest -descriptor <set.pb> -out <manifest.json>")
		os.Exit(2)
	}
	if err := run(*descPath, *outPath); err != nil {
		fmt.Fprintln(os.Stderr, "msgmanifest:", err)
		os.Exit(1)
	}
}

func run(descPath, outPath string) error {
	raw, err := os.ReadFile(descPath)
	if err != nil {
		return err
	}
	var set descriptorpb.FileDescriptorSet
	if err := gogoproto.Unmarshal(raw, &set); err != nil {
		return fmt.Errorf("decode %s: %w", descPath, err)
	}

	types := map[string]bool{}                // every message and enum, fully qualified
	msgInputs := map[string]map[string]bool{} // package -> Msg-service input types
	var modules []string
	moduleMsgs := map[string][]string{}

	for _, file := range set.File {
		pkg := file.GetPackage()
		for _, m := range file.MessageType {
			types[pkg+"."+m.GetName()] = true
		}
		for _, e := range file.EnumType {
			types[pkg+"."+e.GetName()] = true
		}
		for _, svc := range file.Service {
			if svc.GetName() != "Msg" {
				continue
			}
			if msgInputs[pkg] == nil {
				msgInputs[pkg] = map[string]bool{}
			}
			match := twilightPackage.FindStringSubmatch(pkg)
			for _, method := range svc.Method {
				input := strings.TrimPrefix(method.GetInputType(), ".")
				msgInputs[pkg][input] = true
				if match == nil {
					continue
				}
				module := match[1]
				if _, seen := moduleMsgs[module]; !seen {
					modules = append(modules, module)
				}
				moduleMsgs[module] = append(moduleMsgs[module], "/"+input)
			}
		}
	}

	if len(modules) == 0 {
		return fmt.Errorf("%s has no twilight.<module>.v1 Msg service", descPath)
	}
	for _, name := range bankMsgs {
		if !msgInputs["cosmos.bank.v1beta1"][name] {
			return fmt.Errorf("%s is not a method of cosmos.bank.v1beta1.Msg in %s", name, descPath)
		}
	}
	for _, f := range envelope {
		if !types[f.value] {
			return fmt.Errorf("envelope type %s is not in %s", f.value, descPath)
		}
	}
	for _, name := range signerPubKeys {
		if !types[name] {
			return fmt.Errorf("signer key type %s is not in %s", name, descPath)
		}
	}

	var bank []string
	for _, name := range bankMsgs {
		bank = append(bank, "/"+name)
	}
	var keys []string
	for _, name := range signerPubKeys {
		keys = append(keys, "/"+name)
	}

	var b bytes.Buffer
	b.WriteString("{\n")
	fmt.Fprintf(&b, "  \"note\": %s,\n", quote(note))
	fmt.Fprintf(&b, "  \"descriptor_set\": %s,\n", quote("twilight-descriptors.pb"))
	b.WriteString("  \"envelope\": {\n")
	for _, f := range envelope {
		fmt.Fprintf(&b, "    %s: %s,\n", quote(f.key), quote(f.value))
	}
	fmt.Fprintf(&b, "    %s: %s\n", quote("signer_pubkey_any_types"), list(keys, "    "))
	b.WriteString("  },\n")
	b.WriteString("  \"modules\": {\n")
	fmt.Fprintf(&b, "    %s: %s", quote("bank"), list(bank, "    "))
	for _, module := range modules {
		fmt.Fprintf(&b, ",\n    %s: %s", quote(module), list(moduleMsgs[module], "    "))
	}
	b.WriteString("\n  }\n}\n")

	return os.WriteFile(outPath, b.Bytes(), 0o644)
}

// quote encodes s as a JSON string without escaping '<', '>' or '&', so the
// note's arrows stay readable.
func quote(s string) string {
	var b bytes.Buffer
	enc := json.NewEncoder(&b)
	enc.SetEscapeHTML(false)
	_ = enc.Encode(s)
	return strings.TrimSuffix(b.String(), "\n")
}

func list(items []string, indent string) string {
	var b strings.Builder
	b.WriteString("[\n")
	for i, item := range items {
		b.WriteString(indent + "  " + quote(item))
		if i < len(items)-1 {
			b.WriteString(",")
		}
		b.WriteString("\n")
	}
	b.WriteString(indent + "]")
	return b.String()
}
